run:
    timeout: 5m
    issues-exit-code: 1
    tests: true
    modules-download-mode: readonly

linters:
    enable:
        - errcheck
        - gofmt
        - goimports
        - govet
        - ineffassign
        - staticcheck
        - unused

    disable:
        - gochecknoglobals
        - gochecknoinits

issues:
    exclude-rules:
        - path: _test\.go
          linters:
              - errcheck
              - unused
        - path: testutils/
          linters:
              - errcheck
              - unused