# GoReleaser 設定（オプション）
builds:
    - env:
          - CGO_ENABLED=0
      ldflags:
          - -s -w
          - -X main.version={{.Version}}
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64
      ignore:
          - goos: windows
            goarch: arm64
          - goos: darwin
            goarch: arm64

archives:
    - format: tar.gz
      name_template: "git-mini-commit_{{.Os}}_{{.Arch}}"
      files:
          - README.md
          - LICENSE

checksum:
    name_template: "checksums.txt"

snapshot:
    name_template: "{{ incpatch .Version }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
